navikt/sykefravarsstatistikk

- package-lock.json
- package.json
- src/index.tsx
Får vurdere om dette er et behov ennå
> Legg til polyfill så appen fungerer i IE

- src/App.tsx
- src/FeilSider/FeilFraAltinnSide/FeilFraAltinnSide.less
- src/FeilSider/FeilFraAltinnSide/FeilFraAltinnSide.tsx
- src/FeilSider/ManglerRettigheterIAltinnSide/ManglerRettigheterIAltinnSide.less
Tidligere har bruker fått evig spinner. Viser nå samme feilmelding som MSA i stedet.
> Legg til feilmelding hvis kall til MSA feiler

- src/GrafOgTabell/Graf/Graf.tsx
- src/GrafOgTabell/Graf/grafLegend/grafLegend.tsx
Labels var hardkodet. I denne PR-en bruker jeg labels vi får fra backend.
> Gi labels til graf

- src/Forside/VideoerPanel/VideoerPanelTogglet.less
- src/Forside/VideoerPanel/VideoerPanelTogglet.tsx
Endret på tekst på panelet + navn på eventen i amplitude til å matche den nye teksten
> Tekstendring videopanel

- package-lock.json
- src/Forside/Sammenligningspanel/MaskertSykefraværprosentpanel/DataKanIkkeVisesPanel/DataKanIkkeVisesPanel.less
- src/Forside/Sammenligningspanel/MaskertSykefraværprosentpanel/DataKanIkkeVisesPanel/DataKanIkkeVisesPanel.tsx
- src/Forside/Sammenligningspanel/MaskertSykefraværprosentpanel/MaskertSykefraværsprosentpanel.test.tsx
- src/Forside/Sammenligningspanel/Sammenligningspanel.less
jeg prøver å få testen MaskertSykefraværprosentpanel.test.tsx til å kjøre i samme PR, ikke nødvendig.
>  fikse størrelse for datakanikkevisespanel

- .github/workflows/build-deploy.yml
- nais/dev-sbs.yaml
- src/Kalkulator/Kalkulator.less
- src/Kalkulator/Kalkulator.tsx
- src/Kalkulator/Kostnad/Kostnad.less
- src/Kalkulator/Kostnad/Kostnad.tsx
- src/Kalkulator/kalkulator-utils.ts
Set fraction til 2 og set default state{nåværendeTapteDagsverk} til 0  for å unngå undefind
> Forbedring kalkis v2

- src/mocking/sykefraværshistorikk.ts
This reverts commit e2b3ad6d20a61a33a60369863516d8310198f7d4.
> Revert "Revert "Gi mocken 'nye' tall for brukertest""

- src/App.tsx
- src/FeilSider/ManglerRettigheterIAltinnSide/ManglerRettigheterIAltinnSide.tsx
- src/FeilSider/ManglerRettigheterIAltinnSide/OrganisasjonerMedTilgangListe/OrganisasjonerMedTilgangListe.tsx
- src/Forside/Forside.tsx
- src/GrafOgTabell/GrafOgTabell.tsx
- src/amplitude/amplitude.ts
- src/amplitude/userProperties.ts
- src/api/altinnorganisasjon-api.ts
- src/utils/altinnOrganisasjonerContext.tsx
Sender med antall virksomheter brukeren har tilgang til, og antall virksomheter de har tilgang til sykefravær i. Settes som userProperties i amplitude. Jeg vil gjerne diskutere denne.
> Antall bedrifter

- .github/workflows/build-deploy.yml
- src/App.tsx
- src/amplitude/segmentering.ts
- src/amplitude/userProperties.ts
- src/api/sykefraværshistorikk.ts
Det eneste som gjenstår er å forene oss alle i at dette er riktig segmentering.
> Unngå personidentifiserende info ved å segmentere data

- craco.config.js
- package.json
- src/App.tsx
- src/Kalkulator/KalkulatorNy/KalkulatorNy.less
- yarn.lock
Kan testes ved å f.eks. legge til en <img>-tag uten alt-tekst. Da kjører ikke/bygger ikke appen.
> Legg til uu-linting i bygg

- src/App.tsx
- src/Forside/Forside.tsx
- src/Forside/ForsideWrapper.tsx
- src/amplitude/amplitude.ts
Vi har strengt tatt samme feil i kalkulatoren, kan vurdere å ta dette nå eller vente til vi avslutter AB-testen.
> Ikke send doble events ved sidevisning

- src/Forside/barnehage/DetaljertSammenligning/DetaljertSammenligning.tsx
- src/Forside/barnehage/DetaljertSammenligning/DetaljertSammenligningPanel/DetaljertSammenligningPanel.tsx
- src/Forside/barnehage/SammenligningMedBransje/SammenligningSiste4KvartalerMedBransje.tsx
- src/Forside/barnehage/SammenligningspanelBarnehage/SammenligningspanelBarnehage.tsx
- src/Forside/barnehage/barnehage-utils.ts
- src/amplitude/amplitude.ts
- Sende events ved klikk
- Utvide event med tall fra ny sammenligning
> Målinger for barnehager

- .github/workflows/build-deploy.yml
- server/proxy.js
- src/Forside/barnehage/DetaljertSammenligning/DetaljertSammenligning.tsx
- src/Forside/barnehage/DetaljertSammenligning/LesMer/LesMerKorttid.tsx
- src/Forside/barnehage/DetaljertSammenligning/LesMer/LesMerLangtid.tsx
- src/Forside/barnehage/SammenligningMedBransje/SammenligningSiste4KvartalerMedBransje.tsx
- src/Forside/barnehage/barnehage-utils.ts
- src/amplitude/amplitude.ts
- src/api/api.ts
- src/api/sykefraværsvarighet.ts
- src/mocking/mock.ts
- src/mocking/sykefraværsvarighet.ts
Deployet og testet i dev miljø
> Nytt backend api for historikk og varighet

- src/App.tsx
- src/Forside/barnehage/EkspanderbareTips/EkspanderbareTips.tsx
- src/Forside/barnehage/barnehage-utils.ts
- src/felleskomponenter/tips/TipsVisning.tsx
- src/felleskomponenter/tips/tips-innhold.tsx
- src/felleskomponenter/tips/tips.tsx
Komponenten må tas bort før merge
> Logikk for hvilke tips som skal vises

- src/Forside/barnehage/EkspanderbarSammenligning/DinNæringEllerBransje/DinNæringEllerBransje.less
- src/Forside/barnehage/EkspanderbarSammenligning/DinNæringEllerBransje/DinNæringEllerBransje.tsx
- src/Forside/barnehage/EkspanderbarSammenligning/EkspanderbarSammenligning.less
- src/Forside/barnehage/EkspanderbarSammenligning/EkspanderbarSammenligning.tsx
- src/Forside/barnehage/SammenligningMedBransje/EkspanderbartSammenligningspanel.less
- src/Forside/barnehage/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
Sjekk listen i Figma: https://www.figma.com/file/3XL2zGpuBS0cST0YGMKtiU/Sykefrav%C3%A6rsstatistikk-bransjekonsept?node-id=2407%3A34777
> Justeringer forside

- src/Forside/barnehage/EkspanderbarSammenligning/DinNæringEllerBransje/DinNæringEllerBransje.less
- src/Forside/barnehage/EkspanderbarSammenligning/DinNæringEllerBransje/DinNæringEllerBransje.tsx
- src/Forside/barnehage/SammenligningMedBransje/EkspanderbartSammenligningspanel.less
- src/Forside/barnehage/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
- Fjern blå lenkestyling på panel når panelet åpnes
- Juster tekster og layout i Din Næring-boksen
> Småplukk på forsiden

- src/Forside/barnehage/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
- src/Forside/barnehage/SammenligningMedBransje/SykefraværMetadata.tsx
- src/Forside/barnehage/vurderingstekster.tsx
- src/felleskomponenter/OmGradertSykemelding/OmGradertSykemelding.tsx
- src/felleskomponenter/OmGradertSykmelding/OmGradertSykmelding.less
- src/felleskomponenter/OmGradertSykmelding/OmGradertSykmelding.tsx
Vi bruker begrep "sykmelding" fremfor "sykemelding"
> Fiks skrive feil

- README.md
Hei! 
Snublet over dette repoet da jeg skulle vise en bekjent at NAV utvikler åpent.
Når det i tillegg var en liten skrivefeil jeg kunne rette på, var eksempelet komplett. 
Keep up the good work 🙏
> Korrigert skrivefeil i README

- src/konstanter.ts
- src/utils/app-utils.ts
Skal ikke merges før data for 1. kvartal 2021 er publisert/importert
> Endringer etter publisering 1 kvartal 2021

- .github/workflows/build-deploy.yml
- src/felleskomponenter/tips/tips-innhold.tsx
Lenker blir endret i følge lenke her. 
https://teams.microsoft.com/l/file/39899EF1-DE13-4BB8-90D9-97A014D2555C?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=docx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FTAG-Inkluderendearbeidsliv%2FShared%20Documents%2FGeneral%2FForebygge%20sykefrav%C3%A6r%20(applikasjon)%2FNye%20lenker%20til%20Nettkurs%20pa%CC%8A%20NAV.docx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FTAG-Inkluderendearbeidsliv&serviceName=teams&threadId=19:a630a581583e4aa4abee4b276f5ca8a7@thread.skype&groupId=b820f20d-8f41-4ea7-b658-6c319e27b12f
> bytte lenker til nettkurs

- .github/workflows/build-deploy.yml
- src/Forside/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
- src/metrikker/iatjenester.ts
> Brukt forenklet endepunkt

- .eslintrc
- .husky/pre-commit
- package.json
- server/ia-tjenester-metrikker-proxy.js
- src/App.test.tsx
- src/Forside/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
- src/Forside/vurdering-utils.ts
- src/GrafOgTabell/Graf/grafTooltip/grafTooltip.tsx
- src/Innloggingsside/Innloggingsside.tsx
- src/Kalkulator/kalkulator-utils.ts
- src/api/api-utils.ts
- src/metrikker/iatjenester.ts
- tsconfig.json
- yarn.lock
Det vil nok være noen feil som blir emittet nå ettersom lintingen faktisk virker, kommer kanskje et par commits som fikser de (eventuelt at dere har noen forslag for å justere reglene noe)
Gjort følgende: 
- Fått ESLint til å rapportere ordentlig på feil
- Fått typescript compileren til å bli litt strengere på ubrukte parametere på funksjoner
- Bruker anbefalte eslint regler
- La inn pre-commit hooks som kjører prettier og linting på filene som er staged
> Fix eslint v2

- server/decorator.js
- server/package.json
- server/yarn.lock
Request er deprecated siden august ifjor og blir ikke maintainet. Bytter det ut med axios i stedet.
> Fjerne request dependency

- package.json
- yarn.lock
Fjernet ubrukt(?) dependency `request` (dependabot)
> Prøve å gjøre dependabot glad

- package.json
- yarn.lock
Oppdateringen vil gjøre bedriftsmenyen mer tilgjengelig nåe andre tjenester (som menyen bruker) er utilgjengelige.
> oppdatere bedriftsmeny

- .github/workflows/build-deploy.yml
- nais/dev-gcp.yaml
Bare å sende appen til dev-gcp, ingen endringer i token.
> Sende appen til dev gcp

- .github/workflows/build-deploy.yml
- package.json
- yarn.lock
> Oppdater sec champion kickk off

- .github/workflows/build-deploy.yml
- src/Forside/SammenligningMedBransje/EkspanderbartSammenligningspanel.tsx
- src/GrafOgTabell/GrafOgTabell.tsx
- src/Kalkulator/Kalkulator/Kalkulator.tsx
- src/Kalkulator/Kalkulator/Kalkulatorrad/Kalkulatorrad.tsx
- src/metrikker/IaTjenesterMetrikkerContext.tsx
- src/metrikker/iatjenester.test.ts
- src/metrikker/iatjenester.ts
Poenget er at Kalkulator blir som egen `Kilde` , så tanken er å sende både fot `SYKEFRAVÆRSSTATISTIKK`  og `KALKULATOR` .
> Kalkulator som egen tjeneste

- .github/workflows/build-deploy.yml
- package.json
- yarn.lock
Oppgrader Terser til patch versjon etter varsling fra dependabot
> Fiks sårbarhet i Terser 

- src/Forside/ArbeidsmiljøportalPanel/ArbeidsmiljøportalPanel.tsx
- src/GrafOgTabell/Graf/GrafSymbol/SymbolSvg.tsx
- src/GrafOgTabell/Graf/XAkseTick.tsx
- src/felleskomponenter/PaneltittelMedIkon/PaneltittelMedIkon.tsx
- src/felleskomponenter/tips/TipsBilde/TipsBilde.tsx
skjuler en del ikoner som hovedsakelig fungerer som dekor for skjermlesere
> div uu fiks

- .github/workflows/build-deploy.yml
- package.json
- src/GrafOgTabell/Graf/grafTooltip/grafTooltip.tsx
- src/hooks/useAnalytics.test.tsx
- yarn.lock
https://github.com/navikt/sykefravarsstatistikk/security/dependabot/26
> Update recharts to fix "d3-color vulnerable to ReDoS"

- README.md
- src/Forside/Sammenligningspanel/Sammenligningspaneler.tsx
sender metrikk for levert ia-tjeneste ved nedlasting av sykefraværsstatistikk-siden
> metrikk for nedlasting

- .github/workflows/build-deploy.yaml
- src/Brødsmulesti/brødsmulesti-utils.ts
La til Forebygge fravær i breadcrumbs.
> Breadcrumb fix

- server/yarn.lock
og se om action slutter å funke på grunn av hvems om skapte branch.
> Prøver å gjøre samme endring som dependabot
